### ISSUE TITLE
RC.3.2 still does not resolve missing models and model name Casing issue

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#47]
I see that if the loopback model is public, then the imports refer to it in Title case, whereas if the model is public: false it does not get generated (which creates typing issues in typescript, where the variable types of relational properties is undefined).

And also for such models all imports mention them in lower case (my loopback model names are all lower case) and the property definitions also refer to them in lower case.

here, business model is exporting in lower case, but it is being imported elsewhere in Title case, another model that is private : breview, does not get generated (if i make it public just to carry over the generated model - tmp fix, it would be exported in Title case and I'd need to make all references to change case. It becomes nuance. if a model is private, its service can be skipped, but model is required with new RC.2/3 changes.

```
import {
  Job,
  User,
  breview
} from '../index';

export interface businessInterface {
  brief?: string;    
  jobs?: Array<Job>;
  user?:User;
  reviews?: Array<breview>;
}

export class business implements businessInterface {
  brief: string;  
  jobs: Array<Job>;
  user:User;
  reviews: Array<breview>;
  
  constructor(instance?: business) {
    Object.assign(this, instance);
  }
}
```

**Comment by jonathan-casarrubias** [comment]
LoopBack does not expose private models to strong-remoting, that validation is in the following line:

Reference: https://github.com/strongloop/loopback/blob/master/lib/application.js#L152

Therefore it is no possible to use strong-remoting as it is to get Private Models, I will see if I can get access to the model settings aside the strong-remoting, otherwise I will need to create a pull request adding a new configuration to model-config:

something like

````js
{
  "Room": {
    "dataSource": "db",
    "public": false,
    "modelable": true
  }
}
````

but I think such change will have deep implications and I'm not sure the StrongLoop team will allow this type of change.

So, what I will do as work around, is to set the types of those properties using private models to "any".

I still need to verify why strong-remoting is setting the models CamelCase instead all lower case, this is also coming from strong-remoting and may be out of the scope, unfortunately; It seems you are not using the model naming convention and the bug may come from the origin: loopback and strong-remoting.

I will confirm if there is anything to do with those lowercase named models, else If it turns that it is out of the loopback-sdk-builder I may end int not supporting not conventional model namings.

Regards
Jon

**Comment by jonathan-casarrubias** [comment]
@bajtos is it possible to work in something so we can provide fully typed sdk for typescript?

**Comment by jonathan-casarrubias** [comment]
https://github.com/strongloop/loopback-sdk-angular/issues/188#issuecomment-234621344

**Comment by sprypradeep** [comment]
1. You are right, I did not follow the CamelCase, loopback anyway exported models in camel case. I should be able to do this, if we can not close the problem otherwise.
2. With typing the relations and properties as "any" we should be able to bypass the problem, With "any" we did not have any problems with the beta releases :-) it also solves any unintentional security (exposure). But that conflicts with typing it adequately. parts of related models would be required in client.
3. The problem related to lowercasing isnt appearing for models but only relations (scopes), as those arent CamelCased by strong remoting (perhaps because they do nto intend to expose them anyway).

So the immediate fixinng would be to provide "any' for scopes and properties would hidden model type. that would lead to no errors for everyone (including people like me with wrongly cased model names).

I have to commend your approach to try and providing complete typing, but that doesnt seems to be supported by available tools.

**Comment by sprypradeep** [comment]
Following two changes correct the Title casing for properties and models: (utils.js)

```
    var name = c.name;
    var name = c.name[0].toUpperCase() + c.name.slice(1);

```
 ```
 targetClass = targetClass[0].toUpperCase() + targetClass.slice(1);
  modelClass.sharedClass.ctor.relations[scopeName].targetClass = targetClass;

```

After this we just need to decouple the model and service generation sources, services can be looped from the rest adapter classes, but for models we need to do something like swagger spec generator

https://github.com/strongloop/loopback-swagger/blob/master/lib/specgen/swagger-spec-generator.js#L55-L61

**Comment by jonathan-casarrubias** [comment]
This is good, let me play with it and try to come with the complete solution, hidden services but exposed models.

Still I can think, won't that be a security concern? we would expose data models that some devs may want to fully keep it within the backend, we would be generating and exposing models and properties that may be critical to a system security.

So, on RC4 I will publish the "any" workaround, but we need to think deeper if we actually want to expose models.

Cheers
Jon

**Comment by sprypradeep** [comment]
The point can be contested, but if we assume enough brainstorming was done to get the swagger specs out from loopback, we can skip that discussion until swagger.json also hides models like that. Maybe we can provide a separate flag under sdk settings for model, if that model needs to be hidden. (but then we'd require to keep the typing to "any" for all such models, which may be an overkill).

Probably we can leave that customisation to the developers rather than keeping in the tool. and OOTB generation can just generate all models and exposed APIs.

**Comment by sprypradeep** [comment]
I also had to remove following from the model.ejs to not include model.relations as properties, because it had conflict in User.credentials in case passport is used (which includes another UserCredential model as relation. Also if we're not exporting the relation model interfaces, we can skip including them in models:

now model.ejs for angular2 looks like

```
/* tslint:disable */

export interface <%- modelName %>Interface {
<% for (var property in model.properties) { var meta = model.properties[property]; -%>
  <% if (meta.description) { %>
  /**
   * <%- meta.description %>
   */<% } %>
  <%- property %><%= meta.required ? '' : '?' -%>: <%- getModelType(meta.type) %>;
  <%
  } // for property in model.properties -%>

}

export class <%- modelName %> implements <%- modelName %>Interface {
  <% for (var property in model.properties) { var meta = model.properties[property]; -%>
  <% if (meta.description) { %>
  /**
   * <%- meta.description %>
   */<% } %>
  <%- property %>: <%- getModelType(meta.type) %>;<%
  } // for property in model.properties -%>

  constructor(instance?: <%- modelName %>) {
    Object.assign(this, instance);
  }
}

```

**Comment by jonathan-casarrubias** [comment]
@sprypradeep Thanks for reporting all of these issues, In order to have a better issue organization could you please create a new issue for the different issues you may have?

I will consider this issue just for the Private Models issues, and is going to be fixed in RC4 which Im about to publish, I need the other issues to have its own number id.

Thanks!!
Jon

**Comment by jonathan-casarrubias** [comment]
Types for Private Models - Fixed in RC4
