### ISSUE TITLE
custom services imports and refers to private model

### ISSUE THREAD

**Issue by sprypradeep** [jonathan-casarrubias/loopback-sdk-builder#76]
This error has re-appeared in custom service.ts imports and method parameter: type reference
```

import {
  User,
  UserIdentity,
  UserCredential,
  LoopBackFilter
} from '../../models/index';
....
  public createIdentities(id: any, data: UserIdentity = undefined) {
```

The private / hidden models are referred to in imports and parameteres without the definition getting generated. This one is just an example of service everyone will have.

**Comment by jonathan-casarrubias** [comment]
@sprypradeep thanks for reporting, every version I'm trying to integrate typify and make more and more strict the SDK so this is a similar issue not exactly the same,  is just that now the services -some of them- expect the data with the type instead of any as before.

Also, not sure if you already found it but I have been refactoring the entire thing so small dis-adjustments may appear like the backwards optional properties.

I will fix these issues ASAP and publish in 7.3 version.

Cheers
Jon

**Comment by sprypradeep** [comment]
You are right, its not same but similar. Some of the models that are private but related to (embed or has relations) are mentioned in imports and their respective method signatures. Thank you for acknowledging , looking forward to the fix.

Cheers
Pradeep

**Comment by jonathan-casarrubias** [comment]
Fixed in RC8
